### ISSUE TITLE
Exception in ResolveVimPath after update to v. 1.8

### ISSUE THREAD

**Issue by nchaly** [jaredpar/VsVim#1595]
I've been using Visual Studio 2013, after update to version 1.8.0.0, encounter the following exception at load:
```
System.ArgumentException: Illegal characters in path. 
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) 
at System.IO.Path.IsPathRooted(String path)
at Vim.SystemUtil.EnsureRooted(String currentDirectory, String text) 
at Vim.SystemUtil.ResolveVimPath(String currentDirectory, String text) 
at Vim.Interpreter.VimInterpreter.RunSource(Boolean hasBang, String filePath) 
at Vim.Interpreter.VimInterpreter.RunScript(String[] lines) 
at Vim.Interpreter.VimInterpreter.Vim-Interpreter-IVimInterpreter-RunScript(String[] lines) 
at Vim.Vim.LoadVimRcCore() 
at Vim.Vim.LoadVimRc() 
at Vim.Vim.MaybeLoadVimRc() 
at Vim.Vim.GetWindowSettingsForNewBuffer() 
at Vim.Vim.TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer& vimBuffer) 
at Vim.Vim.Vim-IVim-TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer& vimBuffer) 
at Vim.VimCoreExtensions.IVim.GetOrCreateVimBufferForHost(IVim x, ITextView textView) 
at Vim.IncrementalSearchTaggerProvider.Microsoft-VisualStudio-Text-Tagging-IViewTaggerProvider-CreateTagger[T](ITextView textView, ITextBuffer textBuffer) 
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)

```

~~I assume there should be a workaround and I can get rid of illegal characters manually. If only someone can be so nice to give me a hint which directories are being examined?~~

A short debugging session shown that this *vimrc* line is causing troubles:

`source $VIMRUNTIME/mswin.vim	"several windows key bindings`

There is a `TAB` between .vim and quote symbol. I assume it should have been ignored - just as it had been in previous version.

Thank you in advance.

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at this.
