### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by wildeyes** [jaredpar/VsVim#1717]
![vsvimfailed](https://cloud.githubusercontent.com/assets/1652108/11709341/69527d9e-9f1f-11e5-9867-fcb260ead45f.PNG)

View Install Log Gives:

```
10/12/2015 09:16:55 - Microsoft VSIX Installer
10/12/2015 09:16:55 - -------------------------------------------
10/12/2015 09:16:56 - Initializing Install...
10/12/2015 09:16:58 - Extension Details...
10/12/2015 09:16:58 -   Identifier         : VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3
10/12/2015 09:16:58 -   Name               : VsVim
10/12/2015 09:16:58 -   Author             : Jared Parsons
10/12/2015 09:16:58 -   Version            : 2.0.1.0
10/12/2015 09:16:58 -   Description        : VIM emulation layer for Visual Studio
10/12/2015 09:16:58 -   Locale             : en-US
10/12/2015 09:16:58 -   MoreInfoURL        : http://blogs.msdn.com/b/jaredpar
10/12/2015 09:16:58 -   InstalledByMSI     : False
10/12/2015 09:16:58 -   SupportedFrameworkVersionRange : [4.0,5.0]
10/12/2015 09:16:58 - 
10/12/2015 09:16:58 -   SignatureState     : Unsigned
10/12/2015 09:16:58 -   Supported Products : 
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Ultimate
10/12/2015 09:16:58 -           Version : [10.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Ultimate
10/12/2015 09:16:58 -           Version : [11.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Ultimate
10/12/2015 09:16:58 -           Version : [12.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Ultimate
10/12/2015 09:16:58 -           Version : [14.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Premium
10/12/2015 09:16:58 -           Version : [10.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Premium
10/12/2015 09:16:58 -           Version : [11.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Premium
10/12/2015 09:16:58 -           Version : [12.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Premium
10/12/2015 09:16:58 -           Version : [14.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Pro
10/12/2015 09:16:58 -           Version : [10.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Pro
10/12/2015 09:16:58 -           Version : [11.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Pro
10/12/2015 09:16:58 -           Version : [12.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.Pro
10/12/2015 09:16:58 -           Version : [14.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.IntegratedShell
10/12/2015 09:16:58 -           Version : [10.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.IntegratedShell
10/12/2015 09:16:58 -           Version : [11.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.IntegratedShell
10/12/2015 09:16:58 -           Version : [12.0]
10/12/2015 09:16:58 -       Microsoft.VisualStudio.IntegratedShell
10/12/2015 09:16:58 -           Version : [14.0]
10/12/2015 09:16:58 -       AtmelStudio
10/12/2015 09:16:58 -           Version : [6.0]
10/12/2015 09:16:58 -       AtmelStudio
10/12/2015 09:16:58 -           Version : [6.1]
10/12/2015 09:16:58 -       AtmelStudio
10/12/2015 09:16:58 -           Version : [6.2]
10/12/2015 09:16:58 - 
10/12/2015 09:16:58 -   References         : 
10/12/2015 09:16:58 - Signature Details...
10/12/2015 09:16:58 -   Extension is not signed.
10/12/2015 09:16:58 - 
10/12/2015 09:16:58 - Searching for applicable products...
10/12/2015 09:16:58 - System.TypeInitializationException: The type initializer for 'VSIXInstaller.SupportedSKUs' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0.dll' or one of its dependencies. The specified module could not be found.
   at VSIXInstaller.SupportedSKUs.AddInstalledIsolatedShells(Version vsVersion)
   at VSIXInstaller.SupportedSKUs..cctor()
   --- End of inner exception stack trace ---
   at VSIXInstaller.SupportedSKUs.get_SupportedSKUsList()
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Any clue?

**Comment by jaredpar** [comment]
It looks like the VSIX tool is crashing trying to find the VS versions installed on the machine:

```
10/12/2015 09:16:58 - System.TypeInitializationException: The type initializer for 'VSIXInstaller.SupportedSKUs' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0.dll' or one of its dependencies. The specified module could not be found.
   at VSIXInstaller.SupportedSKUs.AddInstalledIsolatedShells(Version vsVersion)
   at VSIXInstaller.SupportedSKUs..cctor()
```

Based on the error message it looks like you're trying to run this on a machine with VS 2015 installed.  If so it looks like the installation may be in a bad state.  Can you try repairing the installation of Visual Studio and see if that fixes the problem?
