### ISSUE TITLE
Visual Studio crash

### ISSUE THREAD

**Issue by AEABryce** [jaredpar/VsVim#1851]
Microsoft Visual Studio Version 14.0.25422.01 Update 3
Plugin VsVim 2.1.1.0

Sometimes on complex projects, I try to autocomplete an "override" method, and it pops up an error message (and stops the current operation) with a pointer to a log file which contains this:

(Sorry for the screwed up stack dump, some of the stuff in this raw text is being converted to markdown.  And I guess there's a chance that this is a Visual Studio bug and not a VsVim bug, so if it's a problem in Visual Studio, I can try submitting it to Microsoft instead.  But VsVim is sitting in the middle of the stack, I think they're more likely to blame the plugin owner first.)

System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetNthTypeParameter(INamedTypeSymbol typeSymbol, Int32 n)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeParameterSymbol(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeSymbol()
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeArguments(List`1 typeArguments)
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(INamespaceOrTypeSymbol container, String name, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(IReadOnlyList`1 containers, String name, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseNamedSymbol(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.Parse(String id, Compilation compilation, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.GetFirstSymbolForId(String id, Compilation compilation)
 at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.DecodeSymbols(List`1 ids, Compilation compilation, List`1 symbols)
 at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.<GetSymbolsAsync>d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetTextChangeAsync>d__26.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.<GetChangeAsync>d__3.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetChangeAsync>d__31.MoveNext()
 --- End of inner exception stack trace ---
 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
 at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
 at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Commit(PresentationItem item, Model model, Nullable`1 commitChar, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Commit(PresentationItem item, Model model, Nullable`1 commitChar)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnTypeChar(Char ch)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
 at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(CommandArgs args, Action nextHandler, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
 at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractXmlTagCompletionCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
 at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.HandlePossibleTypingCommand(CommandArgs args, Action nextHandler, Action`1 actionIfInsideActiveSpan)
 at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers[T](IList`1 commandHandlers, T args, Action lastHandler)
 at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute[T](IContentType contentType, T args, Action lastHandler)
 at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteTypeCharacter(IntPtr pvaIn, ITextBuffer subjectBuffer, IContentType contentType, Action executeNextCommandTarget)
 at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio2000(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut, ITextBuffer subjectBuffer, IContentType contentType)
 at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Vim.VisualStudio.Extensions.Exec(IOleCommandTarget oleCommandTarget, OleCommandData oleCommandData)
 at Vim.VisualStudio.VsCommandTarget.TryCustomProcess(InsertCommand command)
 at Vim.VisualStudio.VsVimHost.TryCustomProcess(ITextView textView, InsertCommand command)
 at Vim.UI.Wpf.VimHost.Vim.IVimHost.TryCustomProcess(ITextView textView, InsertCommand command)
 at Vim.InsertUtil.RunInsertCommandCore[a](InsertCommand command, a addNewLines)
 at Vim.Modes.Insert.InsertMode.RunInsertCommand(InsertCommand command, KeyInputSet keyInputSet, CommandFlags commandFlags)
 at Vim.Modes.Insert.InsertMode.ProcessCore(KeyInput keyInput)
 at Vim.Modes.Insert.InsertMode.Process(KeyInput keyInput)
 at Vim.Modes.Insert.InsertMode.Vim-IMode-Process(KeyInput keyInput)
 at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
 at <StartupCode$Vim-Core>.$VimBuffer.processSet@453(VimBuffer x, FSharpRef`1 processResult, KeyInputSet keyInputSet)
 at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
 at Vim.VimBuffer.Process(KeyInput keyInput)
 at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
 at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.TryProcessWithBuffer(KeyInput keyInput)
 at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Exec(EditCommand editCommand, Action& action)
 at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Vim.VisualStudio.ICommandTarget.Exec(EditCommand editCommand, Action& action)
 at Vim.VisualStudio.VsCommandTarget.Exec(EditCommand editCommand, Action& action)
 at Vim.VisualStudio.VsCommandTarget.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& commandGroup, UInt32 commandId, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at NoahRichards.AlignAssignments.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Text.Formatting.Implementation.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
 at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
 at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) ---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetNthTypeParameter(INamedTypeSymbol typeSymbol, Int32 n)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeParameterSymbol(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeSymbol()
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeArguments(List`1 typeArguments)
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(INamespaceOrTypeSymbol container, String name, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(IReadOnlyList`1 containers, String name, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseNamedSymbol(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.Parser.Parse(String id, Compilation compilation, List`1 results)
 at Microsoft.CodeAnalysis.SymbolId.GetFirstSymbolForId(String id, Compilation compilation)
 at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.DecodeSymbols(List`1 ids, Compilation compilation, List`1 symbols)
 at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.<GetSymbolsAsync>d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetTextChangeAsync>d__26.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.<GetChangeAsync>d__3.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetChangeAsync>d__31.MoveNext()

**Comment by AEABryce** [comment]
Sorry, I should have done more testing, it occurs even without the VsVim plugin involved.

**Comment by jaredpar** [comment]
No worries.  That stack trace is actually interesting to me because it involves my real job: working on [dotnet/roslyn](https://github.com/dotnet/roslyn).   😄 

Good news is that bug should be fixed in the latest source code.  That class responsible was actually deleted and reimplemented.  Fix should show up in Dev15.
