### ISSUE TITLE
Timespan issue when loading solution

### ISSUE THREAD

**Issue by Tobberoth** [jaredpar/VsVim#1860]
When opening a specific solution in Visual Studio 2015, I get an error message and VsVim stops working properly (text cursor doesn't seem to move, slowdowns). It works fine in my other solutions.

VsVim is updated to the latest version.

Here's the error from the ActivityLog (sorry, can't seem to force decent formatting):<br/><br/>

<entry>
    <record>871</record>
    <time>2016/11/11 09:48:52.645</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
System.ArgumentOutOfRangeException: TimeSpan period must be less than or equal to Int32.MaxValue.
Parameter name: interval 
    at System.Windows.Threading.DispatcherTimer..ctor(TimeSpan interval, DispatcherPriority priority, EventHandler callback, Dispatcher dispatcher)   
    at Vim.UI.Wpf.Implementation.BlockCaret.BlockCaret..ctor(ITextView textView, IClassificationFormatMap classificationFormatMap, IEditorFormatMap formatMap, IAdornmentLayer layer, IControlCharUtil controlCharUtil, IProtectedOperations protectedOperations)&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.BlockCaret.BlockCaretFactoryService.CreateBlockCaret(IWpfTextView textView)
    at Vim.UI.Wpf.Implementation.BlockCaret.BlockCaretFactoryService.Vim.IVimBufferCreationListener.VimBufferCreated(IVimBuffer vimBuffer)
    at &lt;StartupCode$Vim-Core&gt;.$Vim.CreateVimBuffer@598-1.Invoke(Lazy`1 x)
    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
    at Vim.Vim.CreateVimBuffer(ITextView textView, FSharpOption`1 windowSettings)
    at Vim.Vim.TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer&amp; vimBuffer)
    at Vim.Vim.Vim-IVim-TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer&amp; vimBuffer)
    at Vim.VisualStudio.HostFactory.Microsoft.VisualStudio.Text.Editor.IWpfTextViewCreationListener.TextViewCreated(IWpfTextView textView)
    at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.&lt;&gt;c__DisplayClass241_0.&lt;BindContentTypeSpecificAssets&gt;b__1()
    at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
  </entry>
  <entry>
    <record>872</record>
    <time>2016/11/11 09:48:52.676</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
System.NullReferenceException: Object reference not set to an instance of an object.
    at Vim.UI.Wpf.Implementation.BlockCaret.BlockCaret.OnCaretPositionChanged(Object sender, EventArgs e)
    at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
</entry>

**Comment by jaredpar** [comment]
Thanks for reporting this issue. 

There is a machine setting for the blink time for caret.  VsVim tries to honor this setting when drawing the block caret used in normal mode.  It appears that on this particular machine a value is being given back that doesn't work with a `TimeSpan` type.  

But really that doesn't make sense given that it only happens for a specific solution.  Thats's quite baffling.  If it happened for every solution then that would make sense.  I wonder if something in that particular solution is also triggering a change to the machine caret blink time and VsVim is just reading the value after the change.

Either way I will change the code to work around invalid values here.
