### ISSUE TITLE
VsVim crashing VS after migration

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#1895]
I've got a weird one: I was seeing crashes after migrating a simple app (I'll send the solution privately), and VsVim was in the activity log. After I disabled it the crash went away. However, after re-enabling I'm not seeing the issue anymore. Here's the relevant log entries:

```
  <entry>
    <record>1062</record>
    <time>2016/12/30 21:36:30.829</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetIndexOfTextLine(ITextViewLine textLine)
   at Vim.MotionUtil.DisplayLineDown(Int32 count)
   at Vim.MotionUtil.GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.MotionUtil.Vim-IMotionUtil-GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.CommandUtil.MoveCaretToMotion(Motion motion, FSharpOption`1 count)
   at Vim.CommandUtil.RunNormalCommand(NormalCommand command, CommandData data)
   at Vim.CommandUtil.RunCommand(Command command)
   at Vim.CommandUtil.Vim-ICommandUtil-RunCommand(Command command)
   at Vim.CommandRunner.Run(KeyInput ki)
   at Vim.CommandRunner.Vim-ICommandRunner-Run(KeyInput ki)
   at Vim.Modes.Normal.NormalMode.Process(KeyInput keyInput)
   at Vim.Modes.Normal.NormalMode.Vim-IMode-Process(KeyInput keyInput)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
   at &lt;StartupCode$Vim-Core&gt;.$VimBuffer.processSet@454.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
  </entry>
  <entry>
    <record>1063</record>
    <time>2016/12/30 21:36:30.850</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetIndexOfTextLine(ITextViewLine textLine)
   at Vim.MotionUtil.DisplayLineDown(Int32 count)
   at Vim.MotionUtil.GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.MotionUtil.Vim-IMotionUtil-GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.CommandUtil.MoveCaretToMotion(Motion motion, FSharpOption`1 count)
   at Vim.CommandUtil.RunNormalCommand(NormalCommand command, CommandData data)
   at Vim.CommandUtil.RunCommand(Command command)
   at Vim.CommandUtil.Vim-ICommandUtil-RunCommand(Command command)
   at Vim.CommandRunner.Run(KeyInput ki)
   at Vim.CommandRunner.Vim-ICommandRunner-Run(KeyInput ki)
   at Vim.Modes.Normal.NormalMode.Process(KeyInput keyInput)
   at Vim.Modes.Normal.NormalMode.Vim-IMode-Process(KeyInput keyInput)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
   at &lt;StartupCode$Vim-Core&gt;.$VimBuffer.processSet@454.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.TryProcessWithBuffer(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Exec(EditCommand editCommand, Action&amp; action)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Vim.VisualStudio.ICommandTarget.Exec(EditCommand editCommand, Action&amp; action)
   at Vim.VisualStudio.VsCommandTarget.Exec(EditCommand editCommand, Action&amp; action)
   at Vim.VisualStudio.VsCommandTarget.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid&amp; commandGroup, UInt32 commandId, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at TrailingWhitespace.WhitespaceRemoverCommand.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\trailingwhitespace\src\Commands\RemoveWhitespaceCommand.cs:line 33
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at TrailingWhitespace.RemoveWhitespaceOnSave.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\trailingwhitespace\src\Commands\RemoveWhitespaceOnSave.cs:line 37
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
  </entry>
```

**Comment by jaredpar** [comment]
Can't reproduce but just looks lke I'm missing a null check in this code path.

**Comment by 333fred** [comment]
Apparently not quite as gone as originally hoped:
```
System.NullReferenceException: Object reference not set to an instance of an object.
	at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetIndexOfTextLine(ITextViewLine textLine)
	at Vim.MotionUtil.DisplayLineDown(Int32 count)
	at Vim.MotionUtil.GetMotion(Motion motion, MotionArgument motionArgument)
	at Vim.MotionUtil.Vim-IMotionUtil-GetMotion(Motion motion, MotionArgument motionArgument)
	at Vim.CommandUtil.MoveCaretToMotion(Motion motion, FSharpOption`1 count)
	at Vim.CommandUtil.RunNormalCommand(NormalCommand command, CommandData data)
	at Vim.CommandRunner.Run(KeyInput ki)
	at Vim.CommandRunner.Vim-ICommandRunner-Run(KeyInput ki)
	at Vim.Modes.Normal.NormalMode.Process(KeyInput keyInput)
	at Vim.Modes.Normal.NormalMode.Vim-IMode-Process(KeyInput keyInput)
	at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
	at &lt;StartupCode$Vim-Core&gt;.$VimBuffer.processSet@485(VimBuffer x, FSharpRef`1 processResult, KeyInputSet keyInputSet)
	at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
	at Vim.VimBuffer.Process(KeyInput keyInput)
	at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
	at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.TryProcessWithBuffer(KeyInput keyInput)
	at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Exec(EditCommand editCommand, Action&amp; action)
	at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Vim.VisualStudio.ICommandTarget.Exec(EditCommand editCommand, Action&amp; action)
	at Vim.VisualStudio.VsCommandTarget.Exec(EditCommand editCommand, Action&amp; action)
	at Vim.VisualStudio.VsCommandTarget.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid&amp; commandGroup, UInt32 commandId, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at TrailingWhitespace.WhitespaceRemoverCommand.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\trailingwhitespace\src\Commands\RemoveWhitespaceCommand.cs:line 33
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at TrailingWhitespace.RemoveWhitespaceOnSave.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\trailingwhitespace\src\Commands\RemoveWhitespaceOnSave.cs:line 37
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
	at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
	at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
	at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
	at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
	at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
Only time I've managed to reproduce this since.

**Comment by ricksladkey** [comment]
@333fred The fix @jaredpar committed for this did not make it into the VsVim 2.5.0 release on 1/5/2018, 11:44:47 AM. It will be in the next release!
