### ISSUE TITLE
VsVim crash in Xamarin XAML source editor

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#1904]
I got this crash when switching between the design and source views with VS 2017 d15prerel/26120.04 with the Xamarin XAML editor. I couldn't repro consistently, tried again this morning and I didn't see the crash.

```
System.InvalidOperationException: IWpfTextView has not completed its layout.
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(ITextSnapshot newSnapshot, ITextSnapshot newVisualSnapshot, SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DisplayTextLineContainingBufferPosition(SnapshotPoint bufferPosition, Double verticalDistance, ViewRelativePosition relativeTo, Nullable`1 viewportWidthOverride, Nullable`1 viewportHeightOverride)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.InnerEnsureVisible()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoActionThatShouldOnlyBeDoneAfterViewIsLoaded(Action action)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.EnsureVisible()
   at Vim.TextViewUtil.EnsureCaretOnScreen(ITextView textView)
   at Vim.TextViewUtil.MoveCaretToCommon[a](ITextView textView, a flags)
   at Vim.TextViewUtil.MoveCaretToPointRaw[a](ITextView textView, SnapshotPoint point, a flags)
   at Vim.TextViewUtil.MoveCaretToPoint(ITextView textView, SnapshotPoint point)
   at Vim.CommonOperations.AdjustCaretForVirtualEdit()
   at Vim.CommonOperations.EnsureAtPoint(SnapshotPoint point, ViewFlags viewFlags)
   at Vim.CommonOperations.Vim-ICommonOperations-EnsureAtCaret(ViewFlags viewFlags)
   at Vim.Modes.Normal.NormalMode.OnEnter(ModeArgument arg)
   at Vim.Modes.Normal.NormalMode.Vim-IMode-OnEnter(ModeArgument arg)
   at Vim.ModeMap.SwitchMode(ModeKind kind, ModeArgument arg)
   at Vim.VimBuffer.SwitchMode(ModeKind modeKind, ModeArgument modeArgument)
   at Vim.VimBuffer.Vim-IVimBuffer-SwitchMode(ModeKind kind, ModeArgument arg)
   at &lt;StartupCode$Vim-Core&gt;.$Vim.runInit@313.Invoke(Unit unitVar0)
   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@326-4.Invoke(TextViewLayoutChangedEventArgs _arg2)
   at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable@1777.OnNext(T value)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.h@744.Invoke(Object _arg1, TArgs args)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@325-3.Invoke(Object sender, TextViewLayoutChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by jaredpar** [comment]
The entire point of Initial Mode is to avoid problems like this.  It appears though that the WPF editor can immediately invalidate itself after the initial draw.  Will need to take that into account.
