### ISSUE TITLE
VsVim won't read .vsvimrc if it is a symlink

### ISSUE THREAD

**Issue by mfrischknecht** [jaredpar/VsVim#1929]
I occasionally have to use VS2010 in a different user account (for remote debugging reasons) and figured I'd just link a `.vsvimrc` file in `C:\Users\username` to my `.vsvim` file using `mklink`. Unfortunately, VsVim seems to ignore both hard- and softlinks. If I copy the file over, my settings are loaded correctly.

**Comment by Kleptine** [comment]
Same issue, and very frustrating. :(

**Comment by ricksladkey** [comment]
I was able to reproduce this issue and the problem in my case is not related to VsVim. For comparison, if I try to open the symlinked `.vsvimrc` in any other editor such as Notepad, it results in `Access is denied.`, which is the same error that VsVim is getting:

```
System.UnauthorizedAccessException "Access to the path 'C:\\Users\\jrs\\.vsvimrc' is denied."

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at Vim.FileSystem.ReadAllLinesLatin1(String path) in C:\Build\VsVim\Src\VimCore\FileSystem.fs:line 49
   at <StartupCode$Vim-Core>.$FileSystem.all@73-2.Invoke(String arg00) in C:\Build\VsVim\Src\VimCore\FileSystem.fs:line 73
   at Vim.FileSystem.ReadAllLinesWithEncoding(String path) in C:\Build\VsVim\Src\VimCore\FileSystem.fs:line 82
   ```

Likewise, if I try to File -> Open -> File in Visual Studio and enter the full path to the symlinked `.vsvimrc` file, Visual Studio reports `The system cannot open the device or file specified. (Exception from HRESULT: 0x8007006E)`.

Conversely, if I symlink `.vsvimrc` to another one of my own files, it works correctly, again leading me to suspect permissions/security issues.

**Comment by ricksladkey** [comment]
Closing this since the reported symptom is not a bug but a consequence of the security model of the underlying filesystem.
