### ISSUE TITLE
VsVim cannot find build tools vs2017 community

### ISSUE THREAD

**Issue by giordi91** [jaredpar/VsVim#1980]
Hei man, sorry to bother, I have been trying to put VsVim on vs2017 as I do for the other version of visual studio, the installer fails complaining cannot find the BuildTools but I have them installed and the path it complains about is there here the actual error:
`06/08/2017 10:20:48 - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`

Any Idea? i have a standard install, nothing weird or anything

**Comment by jaredpar** [comment]
That exception makes me think that the Visual Studio installation itself is busted. Can you try repairing it and seeing if the installation can proceed afterwards?

**Comment by giordi91** [comment]
yeah also the nvidia installer was failing when installing nsight, fresh re-install solved it thanks
