### ISSUE TITLE
VS 2019?

### ISSUE THREAD

**Issue by cmaughan** [jaredpar/VsVim#2453]
I know it's not officially released/supported yet, but I'm wondering if anyone can suggest why I can get the VsVim installer to work on my PC but not my laptop?
i.e. I have VsVim working great in 2019 on my PC with VC 2019 (Preview 1.1), but on my laptop with the same version, the installer just fails....  I've tried both a downloaded installer and adding it from Extensions and Updates....

**Comment by cmaughan** [comment]
Installer log, for what it's worth....

09/01/2019 09:01:48 - Beginning to install extension to Microsoft Visual Studio Enterprise 2019...
09/01/2019 09:01:49 - Found setup instance 73564395 but not in launchable state.
09/01/2019 09:01:49 - Install Error : System.InvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.CreateEngine(IEngineHost engineHost, IServiceProvider serviceProvider, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by cmaughan** [comment]
I figured that this was generic setup issue, so reinstalled the VC2019 installer, and rebooted my laptop.  Finally got it to work.  So I don't think this is VsVim specific....
